[package]
name = "weg"
version = "1.0.0"
edition = "2021"

[dependencies]
image = "0.25.5"
num-bigint = "0.4"
num-traits = "0.1"
[dependencies.nokhwa]
version = "0.10.5"
features = ["input-native", "output-wgpu"]
